repos:
  - repo: https://github.com/rtts/djhtml
    rev: "3.0.10"  # Use the latest stable tag or release
    hooks:
      - id: djhtml
        name: djhtml (HTML/Jinja2 Template Formatter)
        files: ^app/templates/.*\.html$
        args: ["--tabwidth=4"]  # Optional: use 2 or 4 for indentation width

  - repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        args: ["--profile=black"]  # Ensures compatibility with Black formatting
  
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.6
    hooks:
      - id: ruff
  
  # - repo: https://github.com/pycqa/flake8
  #   rev: 7.0.0
  #   hooks:
  #     - id: flake8
  #       language_version: python3
  #      args: ["--max-line-length=88"]  # Match Black's line length

  # - repo: https://github.com/adrienverge/yamllint.git
    # rev: v1.35.1
    # hooks:
      # - id: yamllint
        # files: \.(yml|yaml)$

  # - repo: https://github.com/toml-lang/toml-sort
  #   rev: 0.23.1
  #   hooks:
  #     - id: toml-sort
  #       files: ^pyproject\.toml$

  # - repo: https://github.com/igorshubovych/markdownlint-cli
  #   rev: v0.39.0
  #   hooks:
  #     - id: markdownlint
  #       files: \.(md|markdown)$
